// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4lt7pmMW0hdB-_5YbyGVvQ2aTwUX5LN0',
    appId: '1:516978080624:web:261c9c81a234b8545f6db5',
    messagingSenderId: '516978080624',
    projectId: 'e-store-bddb3',
    authDomain: 'e-store-bddb3.firebaseapp.com',
    storageBucket: 'e-store-bddb3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkDk1HEzgBYzVBgklQ4D925uIGZ3hxpkY',
    appId: '1:516978080624:android:f6a48316852ee8195f6db5',
    messagingSenderId: '516978080624',
    projectId: 'e-store-bddb3',
    storageBucket: 'e-store-bddb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMrGs4Ub21rTtcj6yDVVuKgciJkqx5yFU',
    appId: '1:516978080624:ios:20328599fcbd9c645f6db5',
    messagingSenderId: '516978080624',
    projectId: 'e-store-bddb3',
    storageBucket: 'e-store-bddb3.appspot.com',
    iosBundleId: 'com.example.eStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMrGs4Ub21rTtcj6yDVVuKgciJkqx5yFU',
    appId: '1:516978080624:ios:43247c1d64e659b55f6db5',
    messagingSenderId: '516978080624',
    projectId: 'e-store-bddb3',
    storageBucket: 'e-store-bddb3.appspot.com',
    iosBundleId: 'com.example.eStore.RunnerTests',
  );
}
